-----------------------------------------------------------------------------
--
--    Project Euler 0002
--   
-- |  Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
--    By starting with 1 and 2, 
--    the first 10 terms will be:
--
--    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
--    By considering the terms in the Fibonacci sequence whose values do not exceed four 
--    million, find the sum of the even-valued terms.
-----------------------------------------------------------------------------

module Problem0002 (run) where

        
run :: IO Int
run = return $ prob2 4000000 

prob2 limit = sum . takeWhile (<= limit) . filter even $ fibs 1 2
    where fibs a b = a : fibs b (a+b)
